function cantab_proc();


return


function d = readRawText(file_path)

fid = fopen(file_path,'r');

format_string = '%f %f %*s';

tmp = textscan(fid,

return


function s = textReadStringFormat()

s = [ ...
        '%f ' ...   %     'Subject ID'
        '%*f ' ...            %     'Age'
        '%*s ' ...  %     'NART'
        '%*s ' ...  %     'Gender'
        '%s ' ...   %     'Battery'
        '%f ' ...   %     'Session start time'
        '%f ' ...   %     'SOC Problems solved in minimum moves'
        '%f ' ...   %     'SOC Mean moves (2 moves)'
        '%f ' ...   %     'SOC Mean moves (3 moves)'
        '%f ' ...   %     'SOC Mean moves (4 moves)'
        '%f ' ...   %     'SOC Mean moves (5 moves)'
        '%f ' ...   %     'SOC Mean initial thinking time (2 moves)'
        '%f ' ...   %     'SOC Mean initial thinking time (3 moves)'
        '%f ' ...   %     'SOC Mean initial thinking time (4 moves)'
                    %     'SOC Mean initial thinking time (5 moves)'
                    %     'SOC Mean subsequent thinking time (2 moves)'
                    %     'SOC Mean subsequent thinking time (3 moves)'
                    %     'SOC Mean subsequent thinking time (4 moves)'
                    %     'SOC Mean subsequent thinking time (5 moves)'
                    %     'AGN Mean correct latency (shift, positive)'
                    %     'AGN Mean correct latency (non-shift, positive)'
                    %     'AGN Mean correct latency (shift, negative)'
                    %     'AGN Mean correct latency (non-shift, negative)'
                    %     'AGN Total commissions (shift, positive)'
                    %     'AGN Total commissions (non-shift, positive)'
                    %     'AGN Total commissions (shift, negative)'
                    %     'AGN Total commissions (non-shift, negative)'
                    %     'AGN Total omissions (shift, positive)'
                    %     'AGN Total omissions (non-shift, positive)'
                    %     'AGN Total omissions (shift, negative)'
                    %     'AGN Total omissions (non-shift, negative)'
                    %     'CGT Quality of decision making'
                    %     'CGT Quality of decision making (ascending, 9:1)'
                    %     'CGT Quality of decision making (ascending, 8:2)'
                    %     'CGT Quality of decision making (ascending, 7:3)'
                    %     'CGT Quality of decision making (ascending, 6:4)'
                    %     'CGT Quality of decision making (descending, 9:1)'
                    %     'CGT Quality of decision making (descending, 8:2)'
                    %     'CGT Quality of decision making (descending, 7:3)'
                    %     'CGT Quality of decision making (descending, 6:4)'
                    %     'CGT Risk taking (ascending, 9:1)'
                    %     'CGT Risk taking (ascending, 8:2)'
                    %     'CGT Risk taking (ascending, 7:3)'
                    %     'CGT Risk taking (ascending, 6:4)'
                    %     'CGT Risk taking (descending, 9:1)'
                    %     'CGT Risk taking (descending, 8:2)'
                    %     'CGT Risk taking (descending, 7:3)'
                    %     'CGT Risk taking (descending, 6:4)'
                    %     'CGT Risk adjustment'
                    %     'CGT Risk adjustment (ascending)'
                    %     'CGT Risk adjustment (descending)'
                    %     'CGT Delay aversion'
                    %     'CGT Overall proportion bet'
                    %     'CGT Overall proportion bet (ascending, 9:1)'
                    %     'CGT Overall proportion bet (ascending, 8:2)'
                    %     'CGT Overall proportion bet (ascending, 7:3)'
                    %     'CGT Overall proportion bet (ascending, 6:4)'
                    %     'CGT Overall proportion bet (descending, 9:1)'
                    %     'CGT Overall proportion bet (descending, 8:2)'
                    %     'CGT Overall proportion bet (descending, 7:3)'
                    %     'CGT Overall proportion bet (descending, 6:4)'
                    %     'CGT Deliberation time ascending (9:1)'
                    %     'CGT Deliberation time ascending (8:2)'
                    %     'CGT Deliberation time ascending  (7:3)'
                    %     'CGT Deliberation time ascending (6:4)'
                    %     'CGT Deliberation time (descending, 9:1)'
                    %     'CGT Deliberation time (descending, 8:2)'
                    %     'CGT Deliberation time (descending, 7:3)'
                    %     'CGT Deliberation time (descending, 6:4)'
                    %     'IED Stages completed'
                    %     'IED Total errors'
                    %     'IED Total errors (stage 1)'
                    %     'IED Total errors (stage 2)'
                    %     'IED Total errors (stage 3)'
                    %     'IED Total errors (stage 4)'
                    %     'IED Total errors (stage 5)'
                    %     'IED Total errors (stage 6)'
                    %     'IED Total errors (stage 7)'
                    %     'IED Total errors (stage 8)'
                    %     'IED Total errors (stage 9)'
                    %     'IED Total trials (stage 1)'
                    %     'IED Total trials (stage 2)'
                    %     'IED Total trials (stage 3)'
                    %     'IED Total trials (stage 4)'
                    %     'IED Total trials (stage 5)'
                    %     'IED Total trials (stage 6)'
                    %     'IED Total trials (stage 7)'
                    %     'IED Total trials (stage 8)'
                    %     'IED Total trials (stage 9)'
                    %     'IST Mean number of boxes opened per trial (win condition fixed)'
                    %     'IST Mean number of boxes opened per trial (win condition decreasing)'
                    %     'IST Mean P(correct) (win condition fixed)'
                    %     'IST Mean P(correct) (win condition decreasing)'
                    %     'IST Sampling errors (win condition fixed)'
                    %     'IST Sampling errors (win condition decreasing)'
                    %     'IST Discrimination errors (win condition fixed)'
                    %     'IST Discrimination errors (win condition decreasing)'
                    %     'IST Mean box opening latency (win condition fixed)'
          ];          %     'IST Mean box opening latency (win condition decreasing)'
    
return